/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String _kFontPkg = null;

  static const IconData delete = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_filled = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_regular = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_phone = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_in = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_up = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData api = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dismiss = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData routes = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData near_me = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_bendy = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_double_decker = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_single_decker = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_stop = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error_circle = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData important = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData road_3d = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seat = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData standing = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheelchair = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourite_filled = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourite_regular = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_regular = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_regular = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_filled = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_filled = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_regular = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_filled = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_regular = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
